[[pages]]
path = "homepage.py"
name = "é¦–é¡µ"
icon = "ğŸ "
is_section = false

[[pages]]
path = "chatbot.py"
name = "èŠå¤©æœºå™¨äºº"
icon = "ğŸ¤–"

[[pages]]
path = "data_analysis.py"
name = "æ•°æ®åˆ†æå¸ˆ"
icon = "ğŸ’¹"

[[pages]]
path = "text_to_sql.py"
name = "æ–‡æœ¬ç”ŸæˆSQL"
icon = "ğŸ“„"

[[pages]]
path = "data_engineer.py"
name = "æ•°æ®å·¥ç¨‹å¸ˆ"
icon = "ğŸ—ï¸"


[[pages]]
path = "ml_precess.py"
name = "æœºå™¨å­¦ä¹ æµç¨‹"
icon = "â³"