[[pages]]
path = "webui/homepage.py"
name = "é¦–é¡µ"
icon = "ğŸ "

[[pages]]
path = "webui/chatbot.py"
name = "èŠå¤©æœºå™¨äºº"
icon = "ğŸ¤–"

[[pages]]
path = "webui/data_analysis.py"
name = "æ•°æ®åˆ†æå¸ˆ"
icon = "ğŸ’¹"

[[pages]]
path = "webui/text_to_sql.py"
name = "æ–‡æœ¬ç”ŸæˆSQL"
icon = "ğŸ“„"

[[pages]]
path = "webui/data_engineer.py"
name = "æ•°æ®å·¥ç¨‹å¸ˆ"
icon = "ğŸ—ï¸"


[[pages]]
path = "webui/ml_precess.py"
name = "æœºå™¨å­¦ä¹ æµç¨‹"
icon = "â³"